<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="chassis">

    <xacro:macro name="chassis_visual">
        <visual>
            <origin
                xyz="${aabb_center_x-body_reference_x-0.05} ${aabb_center_y}  ${aabb_center_z-chassis_height+0.1255}"
                rpy="0 0 0" />
            <geometry>
                <mesh filename="package://hunter_description/meshes/chassis.STL" />
                <!-- <box size="${aabb_length} ${aabb_width} ${aabb_height}" /> -->
            </geometry>
        </visual>
    </xacro:macro>


</robot>